Protocol id additions
balancer/balancer-subgraph-v2 pull request #372
Opened 2023-02-13 20:57 UTC by baileyspraggins

# Description

Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas

### `dev` -> `master`
- [ ] I have checked that all beta deployments have synced
- [ ] I have checked that the earliest block in the polygon pruned deployment is <insert block number>, <insert block date/time>
  - [ ] The earliest block is more than 24 hours old
- [ ] I have checked that core metrics are the same in the beta and production deployments

### Merges to `dev`
- [ ] I have checked that the graft base is not a pruned deployment

2023-02-14 12:19 UTC, markusbkoch requested changes

2023-02-14 12:19 UTC, markusbkoch commented on manifest.template.yaml
> +  - kind: ethereum/contract
Since this is a one-off contract, its settings belong in the `datasources` section, not `templates`

2023-02-14 12:19 UTC, markusbkoch commented on schema.graphql
> +  id ID!
```suggestion
  id: ID!
```

2023-02-14 12:19 UTC, markusbkoch commented on schema.graphql
> +  registered: Boolean!
Do you think we need this? Based on the interface you shared, ids can't be deregistered, so it looks redundant as it will always be `true`

2023-03-09 11:22 UTC, markusbkoch requested changes

2023-03-09 11:34 UTC, mendesfabio commented on manifest.template.yaml
> +          handler: handleProtocolIdRegistry
it seems like a create or update function which is common so I'm okay with either renaming it to: `handleProtocolIdRegistryOrRename` or creating one handler for each event.

2023-03-09 11:39 UTC, mendesfabio commented on schema.graphql
> +type ProtocolIdData @entity {
we should create a `protocolIdData` field in the `Pool` entity. Ideally, we wouldn't have the `protocolId` field there, but since we added it before having this contract ready I'd leave it to avoid any breaking changes. wdyt? @markusbkoch

2023-03-09 19:59 UTC, baileyspraggins commented on manifest.template.yaml
> +          handler: handleProtocolIdRegistry
@markusbkoch @mendesfabio I initially had two separate handlers but found the code a little redundant. Ill rename it unless anyone feels strongly about having two handlers

2023-03-10 10:30 UTC, markusbkoch commented on schema.graphql
> +type ProtocolIdData @entity {
Agreed, can you add that @mendesfabio ?

2023-03-10 12:03 UTC, mendesfabio commented on schema.graphql
> +type ProtocolIdData @entity {
done https://github.com/balancer/balancer-subgraph-v2/pull/372/commits/72118ea2d7002d65672a7f59d081cbbdd053b858

2023-03-10 12:13 UTC, mendesfabio approved these changes
I only changed the `protocolId` casting from `toHex()` to `toString()` - using hex the IDs would look like 0x1, 0x2, 0xF, and now they will be 1, 2, 15.

2023-03-10 12:14 UTC, merged