Update for create2 factory deployments
balancer/balancer-subgraph-v2 pull request #430
Opened 2023-04-14 16:19 UTC by baileyspraggins

# Description

Update for the new wave of Linear Pool Factories, which accounts for the `BasePoolFactory` create2 update.

This update adds network tracking and event handlers for the following Linear Pool Factories.
- `AaveLinearPoolV5Factory` (Mainnet, Polygon, Arbitrum, Optimism, BSC, Gnosis)
- `ERC4626LinearPoolV4Factory` (Mainnet, Polygon, Optimism, Arbitrum)
- `GearboxLinearPoolV2Factory` (Mainnet)
- `SiloLinearPoolFactory` (Original Silo Deployment PR was never merged) (Mainnet)
- `YearnLinearPoolV2Factory` (Mainnet, Polygon, Optimism, Arbitrum)

** This PR is currently a draft. Waiting on Mainnet deployment addresses and startBlocks for Yearn, Gearbox, and Silo.**

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas

### `dev` -> `master`
- [ ] I have [checked](https://balancer.github.io/balancer-subgraph-v2/status.html) that all beta deployments have synced
- [ ] I have [checked](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-prune-v2-beta/graphql?query=%0A%7B%0A++balancers%28block%3A%7Bnumber%3A1%7D%29%7B%0A++++id%0A++%7D%0A%7D) that the earliest block in the polygon pruned deployment is [block, date/time](https://polygonscan.com/block/block)
  - [ ] The earliest block is more than 24 hours old
- [ ] I have checked that core metrics are the same in the beta and production deployments

### Merges to `dev`
- [ ] I have checked that the graft base is not a pruned deployment

2023-05-08 13:23 UTC, mendesfabio requested changes

2023-05-08 13:23 UTC, mendesfabio commented on networks.yaml
>    SiloLinearPoolFactory:
this is actually Silo V2, right? could you update it and create the handler?

2023-05-11 07:20 UTC, markusbkoch commented on networks.yaml
>    SiloLinearPoolFactory:
@baileyspraggins yes please, we've been trying to keep the subgraph consistent with onchain calls to `version`

2023-05-12 13:13 UTC, markusbkoch approved these changes

2023-05-12 13:13 UTC, merged