Add protocol fees paid
balancer/balancer-subgraph-v2 pull request #460
Opened 2023-05-26 14:34 UTC by mendesfabio

# Description

Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas

### `dev` -> `master`
- [ ] I have [checked](https://balancer.github.io/balancer-subgraph-v2/status.html) that all beta deployments have synced
- [ ] I have [checked](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-prune-v2-beta/graphql?query=%0A%7B%0A++balancers%28block%3A%7Bnumber%3A1%7D%29%7B%0A++++id%0A++%7D%0A%7D) that the earliest block in the polygon pruned deployment is [block, date/time](https://polygonscan.com/block/block)
  - [ ] The earliest block is more than 24 hours old
- [ ] I have checked that core metrics are the same in the beta and production deployments

### Merges to `dev`
- [ ] I have checked that the graft base is not a pruned deployment

2023-05-29 14:18 UTC, markusbkoch requested changes

2023-05-29 14:18 UTC, markusbkoch commented on schema.graphql
> +  paidProtocolFees: BigDecimal!
```suggestion
  paidProtocolFees: BigDecimal
```
Can't be mandatory because of grafting

2023-05-29 14:18 UTC, markusbkoch commented on src/mappings/poolController.ts
> +      poolToken.paidProtocolFees = poolToken.paidProtocolFees.plus(tokenToDecimal(event.params.value, BPT_DECIMALS));
Need to handle `poolToken.paidProtocolFees == null` because of previous comment

2023-05-29 14:18 UTC, markusbkoch commented on src/mappings/poolController.ts
> +    let protocolFeeCollector = vault.protocolFeesCollector;
`if vault.protocolFeesCollector == null`, set the fee collector. Add TODO to improve on next full sync, when `vault.protocolFeesCollector` can be made a mandatory field guaranteed to be initialized at `findOrInitializeVault`

2023-05-29 14:18 UTC, markusbkoch commented on schema.graphql
> +  protocolFeesCollector: ProtocolFeesCollector
Why the `ProtocolFeesCollector` type and not just an address?

2023-05-29 14:32 UTC, markusbkoch commented on src/mappings/poolFactory.ts
> +  let feesCollectorCall = vaultContract.try_getProtocolFeesCollector();
`findOrInitializeVault` is called on each new pool (and we should probably use it more instead of `Balancer.load(2)` in other parts of the code). To avoid unnecessary calls to `try_getProtocolFeesCollector`, check that `vault.protocolFeesCollector == null` before calling. The fee collector is immutable at the contract level.

2023-05-29 16:33 UTC, mendesfabio commented on schema.graphql
> +  protocolFeesCollector: ProtocolFeesCollector
I thought it could be useful to store other metrics related to fees collected but we can use `Balancer` for that

2023-05-30 07:14 UTC, markusbkoch requested changes

2023-05-30 13:28 UTC, markusbkoch approved these changes

2023-05-30 13:29 UTC, merged