Merge main 20231117
balancer/balancer-subgraph-v2 pull request #531
Opened 2023-11-17 14:56 UTC by franzns

# Description

Adding fantom code into the subgraph but not breaking existing functionality. If we could carry these changes, that would make updating for us a lot easier and faster.

2023-11-27 12:30 UTC, franzns commented
I am waiting for the test deployment to finish before opening the PR https://thegraph.com/hosted-service/subgraph/beethovenxfi/balancer-v2-test?selected=logs

2023-12-06 12:31 UTC, franzns commented
subgraph successfully synced

2023-12-06 12:40 UTC, markusbkoch requested changes
Spotted a few typos and apparently a missing definition. Notice [reaper pools are not indexed](https://api.thegraph.com/subgraphs/name/beethovenxfi/balancer-v2-test/graphql?query=%7B%0A++pools+%28where%3A%7BpoolType%3A%22ReaperLinear%22%7D%29+%7B%0A++++id%0A++%7D%0A%7D)

2023-12-06 12:40 UTC, markusbkoch commented on manifest.template.yaml
> +          handler: handleNewReaperLinearPoolV2
I don't think this handler is defined

2023-12-06 12:40 UTC, markusbkoch commented on networks.yaml
> +  YearnLinearPoolV2:
```suggestion
  YearnLinearPoolV2Factory:
```

2023-12-07 07:56 UTC, franzns commented
> Spotted a few typos and apparently a missing definition. Notice [reaper pools are not indexed](https://api.thegraph.com/subgraphs/name/beethovenxfi/balancer-v2-test/graphql?query=%7B%0A++pools+%28where%3A%7BpoolType%3A%22ReaperLinear%22%7D%29+%7B%0A++++id%0A++%7D%0A%7D)

Thank you Markus, you saved me some headaches here :) Added the changes.

2023-12-07 11:55 UTC, markusbkoch commented
> Thank you Markus, you saved me some headaches here :) Added the changes.

Would you like to redeploy for a final check before merging?

2023-12-07 12:40 UTC, markusbkoch commented
I don't see a problem, marking it as draft until then. Thanks.

2023-12-18 11:55 UTC, franzns commented
Subgraph completed and it looks good. Seems our "old" subgraph has one more pool but I believe that's from a factory that is not in use. Seems good to merge 👍

2023-12-22 16:57 UTC, mendesfabio approved these changes

2023-12-22 16:57 UTC, merged