Refactoring update pool weights
balancer/balancer-subgraph-v2 pull request #541
Opened 2023-12-08 19:49 UTC by thetroyharris

# Description

Refactoring of the `updatePoolWeights` function to no longer uses calls to retrieve token weight information. Instead this token weight information is calculated given the block time and last `GradualWeightUpdateScheduled` event information.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [x] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas

### `dev` -> `master`
- [ ] I have [checked](https://balancer.github.io/balancer-subgraph-v2/status.html) that all beta deployments have synced
- [ ] I have [checked](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-prune-v2-beta/graphql?query=%0A%7B%0A++balancers%28block%3A%7Bnumber%3A1%7D%29%7B%0A++++id%0A++%7D%0A%7D) that the earliest block in the polygon pruned deployment is [block, date/time](https://polygonscan.com/block/block)
  - [ ] The earliest block is more than 24 hours old
- [ ] I have checked that core metrics are the same in the beta and production deployments

### Merges to `dev`
- [ ] I have checked that the graft base is not a pruned deployment

2023-12-08 19:56 UTC, mendesfabio commented
can change target branch to `dev` and address the lint issues? mark as ready for review when all tests are passing and you want me to take a look 🙏

2023-12-11 13:57 UTC, mendesfabio commented
@thetroyharris is it ready for review? can you verify why there's a diff at `.github/workflows/graph.yml`? you probably branched off `master` instead of `dev` - rebase may fix this

2023-12-11 18:16 UTC, thetroyharris commented
@mendesfabio I am investigating an issue with the results of these changes.

2023-12-11 18:45 UTC, mendesfabio commented
> @mendesfabio I am investigating an issue with the results of these changes.

ok, just let me know when I can get back to review it

2023-12-12 12:55 UTC, mendesfabio commented
@thetroyharris I'm confused if I should start reviewing it - can you please mark as ready for review if that's the case?

2023-12-12 19:13 UTC, mendesfabio requested changes

2023-12-12 19:51 UTC, thetroyharris commented on src/mappings/helpers/weighted.ts
> +    if (startWeights.length == tokensList.length) {
Isn't that happening on lines 55:61?

2023-12-12 19:54 UTC, mendesfabio commented on src/mappings/helpers/weighted.ts
> +    if (startWeights.length == tokensList.length) {
I guess I started reviewing your PR before you rebased with `dev` and pulled latest changes - yea that should work

2023-12-12 21:31 UTC, thetroyharris commented on src/mappings/helpers/weighted.ts
> +class GradualValueChange {
Thank you for explaining. I have made the requested changes.

2023-12-12 21:41 UTC, thetroyharris commented on src/mappings/helpers/weighted.ts
> +  if (latestWeightUpdateId === null) {
Thanks for letting me know! Requested changes have been made.

2023-12-13 00:52 UTC, thetroyharris commented
I will be building locally moving forward to decrease the frequency of the CI tests. My apologies.

2023-12-13 10:39 UTC, mendesfabio commented
yes you should run `build` and `lint` locally before pushing changes

2023-12-13 13:02 UTC, thetroyharris commented on src/mappings/vault.ts
>      updateAmpFactor(pool, event.block.timestamp);
Keeping this as is because blockTimestamp is created a few line later and I ran into issues trying to re-declare it.

2023-12-15 13:05 UTC, mendesfabio commented
can you share the deployment URL?

2023-12-15 14:15 UTC, thetroyharris commented
@mendesfabio 

Mainnet: https://api.thegraph.com/subgraphs/id/QmSJZTgfEpeVadrkpNjafFvnpgSVzPxMV3XK1cB9EdDp3Z

Goerli: https://api.thegraph.com/subgraphs/name/thetroyharris/test

2023-12-22 16:46 UTC, merged