Add arbitrum Gyro2V2PoolFactory
balancer/balancer-subgraph-v2 pull request #582
Opened 2024-04-03 16:24 UTC by joshguha

2024-04-03 17:00 UTC, mendesfabio requested changes

2024-04-03 17:00 UTC, mendesfabio commented on networks.yaml
> +    address: "0x8342b910815b0127c98e7717d4276c1d393478b6"
I don't see any events emitted by this contract -- this is probably the implementation, can you verify it?

2024-04-03 17:00 UTC, mendesfabio commented on networks.yaml
> +    address: "0x8342b910815b0127c98e7717d4276c1d393478b6"
I believe this is the factory https://arbiscan.io/address/0x7a36527a02d96693b0af2b70421f952816a4a088

2024-04-04 08:25 UTC, joshguha commented on networks.yaml
> +    address: "0x8342b910815b0127c98e7717d4276c1d393478b6"
Yes @mendesfabio you're completely right! Updated that now

2024-04-05 11:21 UTC, mendesfabio commented on networks.yaml
> +    startBlock: 194366254
```suggestion
    startBlock: 194367293
```

2024-04-10 23:13 UTC, merged